"""Add JobRecommendation and JobMatchReport

Revision ID: 00c3a1040972
Revises: 4a4ac436dcaa
Create Date: 2026-05-28 02:52:41.341774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00c3a1040972'
down_revision: Union[str, None] = '4a4ac436dcaa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_match_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resume_id', sa.Integer(), nullable=False),
    sa.Column('target_jd', sa.Text(), nullable=False),
    sa.Column('analysis_result', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_match_reports_id'), 'job_match_reports', ['id'], unique=False)
    op.create_table('job_recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resume_id', sa.Integer(), nullable=False),
    sa.Column('recommendations', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_recommendations_id'), 'job_recommendations', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_recommendations_id'), table_name='job_recommendations')
    op.drop_table('job_recommendations')
    op.drop_index(op.f('ix_job_match_reports_id'), table_name='job_match_reports')
    op.drop_table('job_match_reports')
    # ### end Alembic commands ###