"""add_enterprise_models

Revision ID: 37709f35dbe6
Revises: b977827be5be
Create Date: 2026-05-30 09:07:41.544463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37709f35dbe6'
down_revision = 'b977827be5be'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enterprise_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enterprise_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('skills_required', sa.JSON(), nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('salary_range', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['enterprise_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_enterprise_jobs_enterprise_id'), 'enterprise_jobs', ['enterprise_id'], unique=False)
    op.create_index(op.f('ix_enterprise_jobs_id'), 'enterprise_jobs', ['id'], unique=False)
    
    op.create_table('job_deliveries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('resume_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('match_score', sa.Integer(), nullable=True),
    sa.Column('analysis_result', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['enterprise_jobs.id'], ),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_deliveries_candidate_id'), 'job_deliveries', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_job_deliveries_id'), 'job_deliveries', ['id'], unique=False)
    op.create_index(op.f('ix_job_deliveries_job_id'), 'job_deliveries', ['job_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_deliveries_job_id'), table_name='job_deliveries')
    op.drop_index(op.f('ix_job_deliveries_id'), table_name='job_deliveries')
    op.drop_index(op.f('ix_job_deliveries_candidate_id'), table_name='job_deliveries')
    op.drop_table('job_deliveries')
    
    op.drop_index(op.f('ix_enterprise_jobs_id'), table_name='enterprise_jobs')
    op.drop_index(op.f('ix_enterprise_jobs_enterprise_id'), table_name='enterprise_jobs')
    op.drop_table('enterprise_jobs')
    # ### end Alembic commands ###