"""Add LearningPathVersion table

Revision ID: 4a4ac436dcaa
Revises: 3c4d5e6f7a8b
Create Date: 2026-05-26 16:02:14.857409

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a4ac436dcaa'
down_revision = '3c4d5e6f7a8b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('learning_path_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resume_id', sa.Integer(), nullable=False),
    sa.Column('interview_session_id', sa.Integer(), nullable=True),
    sa.Column('trigger_type', sa.String(), nullable=False),
    sa.Column('plan_data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['interview_session_id'], ['interview_sessions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learning_path_versions_id'), 'learning_path_versions', ['id'], unique=False)
    op.create_index(op.f('ix_learning_path_versions_interview_session_id'), 'learning_path_versions', ['interview_session_id'], unique=False)
    op.create_index(op.f('ix_learning_path_versions_resume_id'), 'learning_path_versions', ['resume_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_learning_path_versions_resume_id'), table_name='learning_path_versions')
    op.drop_index(op.f('ix_learning_path_versions_interview_session_id'), table_name='learning_path_versions')
    op.drop_index(op.f('ix_learning_path_versions_id'), table_name='learning_path_versions')
    op.drop_table('learning_path_versions')
    # ### end Alembic commands ###