"""Add interview configuration fields

Revision ID: 5d92e5c7bc1e
Revises: 7445f3b0d307
Create Date: 2025-07-11 16:04:06.500979

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "5d92e5c7bc1e"
down_revision = "7445f3b0d307"
branch_labels = None
depends_on = None


def upgrade() -> None:
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    columns = [col["name"] for col in inspector.get_columns("interview_sessions")]

    if "job_position" not in columns:
        op.add_column(
            "interview_sessions", sa.Column("job_position", sa.String(), nullable=True)
        )

    if "interview_mode" not in columns:
        op.add_column(
            "interview_sessions",
            sa.Column("interview_mode", sa.String(), nullable=True),
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("interview_sessions", "interview_mode")
    op.drop_column("interview_sessions", "job_position")
    # ### end Alembic commands ###
