"""add preferences to user

Revision ID: 718b6f1fd7e9
Revises: 95ba00ac2a98
Create Date: 2026-06-03 14:35:07.063990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '718b6f1fd7e9'
down_revision = '95ba00ac2a98'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('preferences', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('preferences')

    # ### end Alembic commands ###