"""add_overall_score_to_interview_sessions

Revision ID: 8b6de8920f32
Revises: 5d92e5c7bc1e
Create Date: 2025-07-12 17:04:33.094819

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "8b6de8920f32"
down_revision = "5d92e5c7bc1e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    columns = [col["name"] for col in inspector.get_columns("interview_sessions")]

    if "overall_score" not in columns:
        op.add_column(
            "interview_sessions",
            sa.Column("overall_score", sa.Integer(), nullable=True),
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("interview_sessions", "overall_score")
    # ### end Alembic commands ###
