"""用于定义数据库结构迁移脚本。"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "8b6de8920f32"
down_revision = "5d92e5c7bc1e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """用于执行数据库升级迁移。"""
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    columns = [col["name"] for col in inspector.get_columns("interview_sessions")]

    if "overall_score" not in columns:
        op.add_column(
            "interview_sessions",
            sa.Column("overall_score", sa.Integer(), nullable=True),
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    """用于执行数据库回滚迁移。"""
    op.drop_column("interview_sessions", "overall_score")
    # ### end Alembic commands ###
