"""add interview fields to job delivery

Revision ID: 95ba00ac2a98
Revises: 37709f35dbe6
Create Date: 2026-06-02 21:46:06.579661

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '95ba00ac2a98'
down_revision = '37709f35dbe6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('target_skills', sa.Text(), nullable=True),
    sa.Column('outline', sa.Text(), nullable=True),
    sa.Column('published', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_courses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_courses_id'), ['id'], unique=False)

    op.create_table('candidate_course_enrollments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['ai_courses.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('candidate_course_enrollments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_candidate_course_enrollments_course_id'), ['course_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_candidate_course_enrollments_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_candidate_course_enrollments_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('agent_events', schema=None) as batch_op:
        batch_op.drop_index('idx_agent_events_session_sequence')

    with op.batch_alter_table('interview_sessions', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('started_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
        batch_op.alter_column('ended_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
        batch_op.drop_index('idx_interview_sessions_resume_id')
        batch_op.drop_index('idx_interview_sessions_resume_status')
        batch_op.drop_index('idx_interview_sessions_status')
        batch_op.create_index(batch_op.f('ix_interview_sessions_resume_id'), ['resume_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_interview_sessions_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_interview_sessions_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('interview_turns', schema=None) as batch_op:
        batch_op.alter_column('asked_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
        batch_op.alter_column('answered_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
        batch_op.drop_index('idx_interview_turns_session_id')
        batch_op.drop_index('idx_interview_turns_session_turn_index')
        batch_op.drop_index('idx_interview_turns_status')
        batch_op.create_index(batch_op.f('ix_interview_turns_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_interview_turns_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_interview_turns_status'), ['status'], unique=False)
        batch_op.drop_constraint('interview_turns_new_session_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'interview_sessions', ['session_id'], ['id'])

    with op.batch_alter_table('job_deliveries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('interview_time', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('interview_location', sa.String(), nullable=True))

    with op.batch_alter_table('optimization_records', schema=None) as batch_op:
        batch_op.drop_index('idx_optimization_records_resume_id')

    with op.batch_alter_table('resume_chat_messages', schema=None) as batch_op:
        batch_op.drop_index('idx_resume_chat_messages_resume_id')
        batch_op.drop_constraint('resume_chat_messages_resume_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'resumes', ['resume_id'], ['id'])

    with op.batch_alter_table('resumes', schema=None) as batch_op:
        batch_op.drop_index('idx_resumes_owner_id')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('is_superuser',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('is_superuser',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    with op.batch_alter_table('resumes', schema=None) as batch_op:
        batch_op.create_index('idx_resumes_owner_id', ['owner_id'], unique=False)

    with op.batch_alter_table('resume_chat_messages', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('resume_chat_messages_resume_id_fkey', 'resumes', ['resume_id'], ['id'], ondelete='CASCADE')
        batch_op.create_index('idx_resume_chat_messages_resume_id', ['resume_id'], unique=False)

    with op.batch_alter_table('optimization_records', schema=None) as batch_op:
        batch_op.create_index('idx_optimization_records_resume_id', ['resume_id'], unique=False)

    with op.batch_alter_table('job_deliveries', schema=None) as batch_op:
        batch_op.drop_column('interview_location')
        batch_op.drop_column('interview_time')

    with op.batch_alter_table('interview_turns', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('interview_turns_new_session_id_fkey', 'interview_sessions', ['session_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_index(batch_op.f('ix_interview_turns_status'))
        batch_op.drop_index(batch_op.f('ix_interview_turns_session_id'))
        batch_op.drop_index(batch_op.f('ix_interview_turns_id'))
        batch_op.create_index('idx_interview_turns_status', ['status'], unique=False)
        batch_op.create_index('idx_interview_turns_session_turn_index', ['session_id', 'turn_index'], unique=False)
        batch_op.create_index('idx_interview_turns_session_id', ['session_id'], unique=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('answered_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('asked_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)

    with op.batch_alter_table('interview_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_interview_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_interview_sessions_status'))
        batch_op.drop_index(batch_op.f('ix_interview_sessions_resume_id'))
        batch_op.create_index('idx_interview_sessions_status', ['status'], unique=False)
        batch_op.create_index('idx_interview_sessions_resume_status', ['resume_id', 'status'], unique=False)
        batch_op.create_index('idx_interview_sessions_resume_id', ['resume_id'], unique=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('ended_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('started_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('agent_events', schema=None) as batch_op:
        batch_op.create_index('idx_agent_events_session_sequence', ['session_id', 'sequence'], unique=False)

    with op.batch_alter_table('candidate_course_enrollments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_candidate_course_enrollments_user_id'))
        batch_op.drop_index(batch_op.f('ix_candidate_course_enrollments_id'))
        batch_op.drop_index(batch_op.f('ix_candidate_course_enrollments_course_id'))

    op.drop_table('candidate_course_enrollments')
    with op.batch_alter_table('ai_courses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_courses_id'))

    op.drop_table('ai_courses')
    # ### end Alembic commands ###