"""用于定义数据库结构迁移脚本。"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a8d672decd64"
down_revision = "8b6de8920f32"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """用于执行数据库升级迁移。"""
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    columns = [col["name"] for col in inspector.get_columns("interview_sessions")]

    if "report_data" not in columns:
        op.add_column(
            "interview_sessions", sa.Column("report_data", sa.JSON(), nullable=True)
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    """用于执行数据库回滚迁移。"""
    op.drop_column("interview_sessions", "report_data")
    # ### end Alembic commands ###
