"""add report_data field to interview_sessions

Revision ID: a8d672decd64
Revises: 8b6de8920f32
Create Date: 2025-07-15 15:45:36.466915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8d672decd64'
down_revision = '8b6de8920f32'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interview_sessions', sa.Column('report_data', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interview_sessions', 'report_data')
    # ### end Alembic commands ###